### ISSUE TITLE
[Feature]Add a Wrapper Command Entry to Run Minecraft under Someother Applations instead of Direct Java

### ISSUE THREAD

**Issue by kuzuanpa** [Steve-xmh/scl#11]
// 功能概述
// 你设想的功能是什么呢？
功能概述：

Add a entry to configure wrapper command infront of "java" 
For example :
The original command is like this:
$ java -Dfile.encoding=UTF-8 -D...[and other args..] 
If I configured the entry ,the command actually executed is like this:
entry: optirun
$ optirun java -Dfile.encoding=UTF-8 -D...[and other args..] 
entry: konsole --hold -e 
$ konsole --hold -e java -Dfile.encoding=UTF-8 -D...[and other args..] 

// 问题关联
// 这个功能与当前启动器的某个短板有关吗？可以引用 Issue 哦！
问题关联：Not at all

// 备注
// 如果还有什么需要提及的话
备注：

Sorry to bother you for this because it's may be useless for most users in most time,but in few condictions it's really useful.

**Comment by poly000** [comment]
could we perform this by edit java command for a prefix?
seems that will work if you do not need provide command in single argument:
(like`foo "$MINECRAFT_COMMAND"`)
