### ISSUE TITLE
[Feature]允许导出Minecraft启动命令

### ISSUE THREAD

**Issue by poly000** [Steve-xmh/scl#12]
// 功能概述
// 你设想的功能是什么呢？
功能概述：
允许导出Minecraft启动命令

// 问题关联
// 这个功能与当前启动器的某个短板有关吗？可以引用 Issue 哦！
问题关联：#11

// 备注
// 如果还有什么需要提及的话
备注：

**Comment by Steve-xmh** [comment]
似乎需求并不强烈，所以推迟到 2.0 再考虑
