### ISSUE TITLE
为单个版本设置单独的JAVA版本启动

### ISSUE THREAD

**Issue by CrnEilns** [Steve-xmh/scl#14]
// 功能概述
// 你设想的功能是什么呢？
功能概述：如题，为单个版本设置单独的JAVA版本启动

// 问题关联
// 这个功能与当前启动器的某个短板有关吗？可以引用 Issue 哦！
问题关联：没有

// 备注
// 如果还有什么需要提及的话
备注：没有

**Comment by Steve-xmh** [comment]
Alpha 0.4.0 之后可以在版本独立设置中输入需要使用的 Java 运行时路径来设置单独的运行时
