### ISSUE TITLE
[Feature] 增加linux版本

### ISSUE THREAD

**Issue by hard2make1name** [Steve-xmh/scl#19]
功能概述：
https://steve-xmh.github.io/scl/index.html：得益于 Rust 的超强跨平台编程能力，Sharp Craft Launcher 能够在   Windows，Linux，MacOS[2] 运行。启动游戏，不再是 C# / Java / 易语言[3] 的专利，更不受各种操作系统的限制。  
  
好的你是这么说的，但是 linux 编译版去哪了  
我不是rust的使用者，但你在readme也没写怎么编译。。  
希望能在readme加一个编译的方法，照顾一下linux用户 : - )  

问题关联：

备注：

**Comment by Steve-xmh** [comment]
嗯，这个仓库是用来存放 SCL 网站源代码的。所以不包含 SCL 的源代码，目前 SCL 还是处于闭源状态，之后会有考虑开源（时间未定）

目前的 Linux 版本和 Mac 版本均处于不稳定状态，所以目前公开的版本均没有提供上面两个平台的构建版本，而内测版本我只提供了 x86_64 构建。内测用户中只有少数 Linux 用户在帮我查找 BUG 和问题。

Mac 构建的话，我已经买了 MacBook 了，还在路上。。。现在是可以构建的，但是因为没有实体机器测试起来非常麻烦，所以得等机器到了才能开始做移植适配工作。

以上，开发难度较大，还请多多理解。
