### ISSUE TITLE
[Feature] 添加离线账户设置UUID的功能

### ISSUE THREAD

**Issue by zkitefly** [Steve-xmh/scl#28]
功能概述：

添加离线账户设置UUID的功能

这样可以挽救那些因为UUID的问题而同时背包物品等事情

也可以做些骚操作qwq

![image](https://user-images.githubusercontent.com/64117916/185655349-32955100-7269-46dc-8537-b9ad50ed81c8.png)

问题关联：

备注：

**Comment by Steve-xmh** [comment]
已完成
