### ISSUE TITLE
添加版本列表排序按钮的提示

### ISSUE THREAD

**Issue by zkitefly** [Steve-xmh/scl#30]
功能概述：

添加版本列表排序按钮的提示

因为不知道是我理解上的问题

这些图标或多或少的让我有点蒙蔽

建议可以通过适当的方式做一些提示

方便用户理解

![image](https://user-images.githubusercontent.com/64117916/185658198-9175fa9b-39b6-4ea3-85c5-84077252dc40.png)

问题关联：

备注：

**Comment by Steve-xmh** [comment]
这个留到 SCL2 之后再做吧

Druid 限制太大了
