### ISSUE TITLE
[Bug] 部分页面底部文字会上抬

### ISSUE THREAD

**Issue by zkitefly** [Steve-xmh/scl#32]
启动器版本号：SharpCraftLauncher-20220818-6df6f3-i686

操作系统及其版本：

![image](https://user-images.githubusercontent.com/64117916/185659734-3fbcc387-1118-4d1e-8cac-6e3c813b594d.png)

问题概述：

部分页面底部文字会上抬

具体详见视频：

https://user-images.githubusercontent.com/64117916/185659284-b31ef8b6-11fe-4024-800e-33b8dc1a96a7.mp4

崩溃报告：
```
一些调试信息……
```

启动参数：
```
java -version
```

重现步骤：

1. 打开启动器
2. 打开设置
3. 选择调试标签页
4. 点击“触发恐慌崩溃”

备注：

**Comment by Steve-xmh** [comment]
已修复
