### ISSUE TITLE
[Feature]支持断点重连下载

### ISSUE THREAD

**Issue by sseaan** [Steve-xmh/scl#35]
功能概述：
若网络在下载游戏本体时断掉,希望可以在连上时从断点继续下载

问题关联：
下载客户端稍微有点慢

备注：

**Comment by Steve-xmh** [comment]
如果下载时被意外中断，其实可以直接重新开始的，原先已经完整下载的文件会被跳过，缩短下载时间。

然后如果遇到下载缓慢的问题，可以在设置里尝试使用其它镜像源，个人推荐 MCBBS 镜像源，速度最佳。

考虑到实际上 SCL 并不支持真正意义上的断点重连或者分片下载（碍于 `surf` 框架的限制不好制作），所以这个 Issue 会留一段时间看能不能优化下载速度。

**Comment by Steve-xmh** [comment]
此功能推迟到 SCL 2 后再制作，届时先关闭 Issue 日后再开
