### ISSUE TITLE
[Bug]微软账号未购买游戏应该会有提示

### ISSUE THREAD

**Issue by frank-782** [Steve-xmh/scl#36]
启动器版本号：nighty #5b90b08f

操作系统及其版本：MacOS 12.2.1 X86_64

问题概述：
微软账号未购买游戏或者账号受限（如<18）启动器应该抛出提示，但当前版本中并没有这些提示，让人以为是网络或者启动器的问题

崩溃报告：
```
无
```

启动参数：
```
java -version
```

重现步骤：

1. 打开启动器
2. 登录未购买游戏的微软账号

备注：

**Comment by Steve-xmh** [comment]
已修复
