### ISSUE TITLE
[Bug]开了版本隔离的版本中，内存设置无法覆盖全局的内存设置。

### ISSUE THREAD

**Issue by 7777777-4547** [Steve-xmh/scl#42]
启动器版本号：1.0.0

操作系统及其版本：Windows 10 x86_64 21H2

问题概述：
 开了版本隔离的版本中，内存设置无法覆盖全局的内存设置。

崩溃报告：
```
无
```

启动参数：
```
java -version
```

重现步骤：

1. 打开启动器
2. 打开版本选择
3. 打开其中一个版本的版本隔离并调一个与全局不同的内存值
4. 启动查看F3上的内存值

备注：

**Comment by Steve-xmh** [comment]
v1.0.1 已修复
