### ISSUE TITLE
[Feature]支持Quilt自动安装

### ISSUE THREAD

**Issue by JieningYu** [Steve-xmh/scl#44]
功能概述：像安装Fabric一样支持自动安装[Quilt](https://quiltmc.org/)

备注：支持Quilt是一个非常有意义与价值的行为

**Comment by Steve-xmh** [comment]
介于 QuiltMC 尚未完全成为一个独立的模组加载器分支（截至目前仍然处于和 Fabric 相互兼容的状态），考虑到集成功能复杂度等因素，Sharp Craft Launcher 将在长期内不会支持 QuiltMC 模组加载器的下载与安装支持。

如有不便之处，还请多多谅解。

[摘自爱发电动态](https://afdian.net/p/3ee698d60eff11ed86af52540025c377)

在之后开源 SCL 启动器核心时，会为核心添加 QuiltMC 的安装功能的。

**Comment by JieningYu** [comment]
quilt自己有独有mod，并非与fabric相互兼容，而是单向兼容。此外有众多整合包使用quilt而非fabric

**Comment by Steve-xmh** [comment]
> quilt自己有独有mod，并非与fabric相互兼容，而是单向兼容。此外有众多整合包使用quilt而非fabric

我的意思是，QuiltMC 是基于 FabricMC 的环境发展而来，在现在它还可以支持 FabricMC 模组加载的情况下 QuiltMC 无异于在割裂模组开发社区，而模组加载器的割裂也会加大启动器开发者的开发和维护负担。并且因为是 Rust 所以增加其安装手段会增加启动器的体积，还有[先前 BakaXL 的事情](https://github.com/QuiltMC/quiltmc.org/issues/51)给我个人留下了不太好的印象，故目前对 QuiltMC 持观望态度，视其状况我会开始着手支持的。

不用过多担心这个功能不会制作，只是现阶段我一没有太多时间二有其它因素，所以请敬候佳音吧，这个 Issue 等考虑开始制作之后我会重新开放的。

**Comment by Steve-xmh** [comment]
重新打开 Issue，预期先在启动器内核这边先做支持，然后再移入 GUI 内

**Comment by Steve-xmh** [comment]
已增加支持，预计下一个次要版本号推出
