### ISSUE TITLE
[Feature] 在主页按 Enter 键启动游戏，按 Esc 返回上级页面的功能

### ISSUE THREAD

**Issue by zkitefly** [Steve-xmh/scl#46]
功能概述：

建议加上在主页按 Enter 键启动游戏，按 Esc 返回上级页面的功能

备注：

可在启动游戏的“你知道吗”中添加相关操作提示

**Comment by Steve-xmh** [comment]
虽然是一个很好的功能，但是受限于 Druid 只能让一个聚焦的组件接收按键事件，所以没办法做（悲）

等日后如果切换到 FLTK 后有条件的话，这个 Issue 会再次开放。
