### ISSUE TITLE
[Bug]启动器在启动Quilt时发生了严重的报错

### ISSUE THREAD

**Issue by rechalow** [Steve-xmh/scl#47]
启动器版本号：SharpCraftLauncher-20220910-0afddd-i686

操作系统及其版本：Windows 11 x86_64

问题概述：首先，我在HMCL里面挂梯子下载了一次Quilt，将其的Libraries和json都下载下来了。【启动器作者应该都懂libraries是什么意思。】然后，我使用SCL启动游戏的时候，就发生了很严重的报错。

通过我检查您的启动参数发现，您似乎并没有在启动游戏的时候对natives文件进行解压。如果你需要图片，我可以提供给你：
![image](https://user-images.githubusercontent.com/61784773/194004890-b8f10a7e-143f-42a2-b214-97cc4515d233.png)
![image](https://user-images.githubusercontent.com/61784773/194004901-4308c107-5da1-4b63-a3b3-71531e077b8d.png)
此时你就应该能发现，你的启动参数中的【-Djava.library.path】一行的natives并没有成功解压到我的本地。
希望能加上【在启动游戏的时候解压natives，而不是在（别的什么时刻）解压natives】。
非常感谢您的回复！

崩溃报告：崩溃报告肯定有的：
[latest.log](https://github.com/Steve-xmh/scl/files/9713644/latest.log)
```
一些调试信息……
```
暂无调试信息

启动参数：刚好，我用的是离线登录，就没必要删掉AccessToken了。我可以发给你我自己用wmic获取到的启动参数：
```
java -version
```
Java 17.0.4.1，Oracle的最新版

重现步骤：

1. 打开启动器
2. 打开设置
3. 选择Java
4. 选择最大内存
5. 打开版本管理
6. 选中Quilt
7. 打开账号登录
8. 进行离线登录
9. 启动游戏

备注：
为什么！为什么步骤这么多？！？！

**Comment by rechalow** [comment]
tnnd，为什么图片上传不了？？

**Comment by Steve-xmh** [comment]
请考虑使用 1.0.0 正式版本再次尝试启动

如果问题仍然存在我会加上标签后续安排时间修复

为了提高启动速度，SCL 只会在启动失败时对游戏文件进行检查（包括对原生运行库的重新解压），如果 SCL 有尝试过自动修复但对应的原生库文件并没有出现的话，有可能是 Quilt 使用了不合规的记录方式记录了原生库的信息。

临时修复手段：把 HMCL 解压的原生库也放一份到 SCL 的原生库应该可以解决

**Comment by rechalow** [comment]
是的，你说的没错。将HMCL的原生库放到SCL里面后，确实启动成功了。
事实上，我刚刚说的情况，也同样能够被算在启动失败的项目中吧。可以为此加上个解压natives的代码吗？

**Comment by Steve-xmh** [comment]
> 是的，你说的没错。将HMCL的原生库放到SCL里面后，确实启动成功了。
> 事实上，我刚刚说的情况，也同样能够被算在启动失败的项目中吧。可以为此加上个解压natives的代码吗？

启动失败修复包含对 natives 文件夹的重新检查，详情看我上面的回复

**Comment by rechalow** [comment]
也许你说的对，据我所知，无论是Forge还是Fabric，又或者是Quilt，其Json文件如出一辙的均为【Json的键libraries中并没有任何附带的原生库。】
如果，SCL能够解压Forge、Fabric对应的inheritsForm键中的原生库，那么就一定能够解压Quilt的原生库。
因为其调用的均为InheritsForm中的原版Json文件。

**Comment by Steve-xmh** [comment]
经过测试，使用 HMCL 安装的 QuiltMC  0.17.5 (Minecraft 1.17.1) 可以通过 SCL 启动（完全按照你所给的步骤进行），第一次启动会失败然后触发自动检查，此时的解压也是正确进行的，没有问题。

![image](https://user-images.githubusercontent.com/39523898/195811411-1ba7dee7-c2c7-4b1a-a61b-fef478aa19b0.png)

演示视频：

https://user-images.githubusercontent.com/39523898/195813287-43952fbd-c31d-4e81-b077-1b56159eb7cf.mp4

**Comment by Steve-xmh** [comment]
如果抱有疑问，请先在内测群内询问群友协助解决，然后再回来重新打开这个 Issue
