### ISSUE TITLE
[Bug] 第三方登录流程错误

### ISSUE THREAD

**Issue by liziyi0914** [Steve-xmh/scl#52]
启动器版本号：20221016-8f1248-i686

操作系统及其版本：Windows 11 x86_64

问题概述：缺少[authlib-injector](https://github.com/yushijinhun/authlib-injector)的[启动器技术规范-账户的添加](https://github.com/yushijinhun/authlib-injector/wiki/%E5%90%AF%E5%8A%A8%E5%99%A8%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E8%B4%A6%E6%88%B7%E7%9A%84%E6%B7%BB%E5%8A%A0)中第五步

重现步骤：

1. 打开启动器
2. 添加第三方登录账户

**Comment by Steve-xmh** [comment]
已修复（大概），预计 1.0.2 推出
