### ISSUE TITLE
[Feature] 修 微软登入

### ISSUE THREAD

**Issue by china-us** [Steve-xmh/scl#53]
功能概述：看https://wiki.vg/Zh:Microsoft_Authentication_Scheme 

问题关联：https://github.com/Steve-xmh/scl/issues/45 可能是？

备注：不希望能在今年修完修完(doge)

**Comment by Steve-xmh** [comment]
请详细说明错误情况，我这里并没有测试出有什么问题

**Comment by china-us** [comment]
转到https://github.com/Steve-xmh/scl/issues/62 继续
