### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MinecraftSTL** [Steve-xmh/scl#58]
启动器版本号：SharpCraftLauncher-20220910-1.0.0-x86_64.exe

操作系统及其版本：Windows 11 x64 AMD

问题概述：皮肤站登录界面缺少滚动条

崩溃报告：
```
一些调试信息……
```

启动参数：
```
java -version
```

重现步骤：

1.使用皮肤站登录，
2.使皮肤站返回信息过长将最底下的按钮顶出界面（如使用
http://hiperauth.tech/api/yggdrasil-hiper
1
1
作为信息登录）

备注：
![Uploading MR`GC~J3IL2FD7N84UMQGCU.png…]()

**Comment by Steve-xmh** [comment]
已修复

然后，请务必写清楚标题，且简明扼要
