### ISSUE TITLE
[Bug]独立版本设置内无法选择”手动调节内存“

### ISSUE THREAD

**Issue by sseaan** [Steve-xmh/scl#60]
启动器版本号：Nightly #8f124852

操作系统及其版本：Windows 11 Pro x86_64

问题概述：独立版本设置内无法选择”手动调节内存“

崩溃报告：
```
一些调试信息……
```

启动参数：
```
java -version
```

重现步骤：

1. 打开启动器
2. 打开版本列表
3. 点击版本设置图标
4. 点击“高级设置”
5. 点击“手动调节内存”

备注：

**Comment by Steve-xmh** [comment]
已修复
