### ISSUE TITLE
[Bug]调教好的设置再重新启动启动器后会失效

### ISSUE THREAD

**Issue by sseaan** [Steve-xmh/scl#61]
启动器版本号：Nightly #8f124852

操作系统及其版本：Windows 11 Pro x86_64

问题概述：调教好的设置再重新启动启动器后会失效

崩溃报告：
```
一些调试信息……
```

启动参数：
```
java -version
```

重现步骤：

1. 打开启动器
2. 打开设置
3. 调整设置
4. 关闭启动器
5. 打开启动器
6. 打开设置

备注：

**Comment by poly000** [comment]
调整设置后是否返回主菜单？

**Comment by sseaan** [comment]
> 调整设置后是否返回主菜单？

返回和未返回都试过，都失效

**Comment by Steve-xmh** [comment]
已修复
