### ISSUE TITLE
[Bug]微软登入fix

### ISSUE THREAD

**Issue by china-us** [Steve-xmh/scl#62]
启动器版本号：
Windows 7 x86_64
操作系统及其版本：Windows 10 x86_64

问题概述：微软登入问题

崩溃报告：正版登录发生错误:SSLConnectFailed(None): unknown error
```
一些调试信息……
```

启动参数：无
```
java -version
```

重现步骤：用微软登入

1. 打开启动器
2. 打开设置
3. 选择调试标签页
4. 点击“触发恐慌崩溃”

备注：这个问题可能是win的SSL问题 
          过时的windows的winSSL过时了

**Comment by Steve-xmh** [comment]
如果通过更新根证书可以修正问题，那就应该不属于启动器的修复范畴

**Comment by china-us** [comment]
算了 不解决问题了

**Comment by Steve-xmh** [comment]
补充：该问题是由于 CURL 通过 Secure Channel 校验证书时吊销服务器无法访问导致，故需要等待日后有机会替换 `surf` 模块方可解决问题。

参考：https://blog.csdn.net/Dancen/article/details/109730392
