### ISSUE TITLE
3个[Bug]

### ISSUE THREAD

**Issue by xuzhichang** [Steve-xmh/scl#67]
启动器版本号：
SharpCraftLauncher-20221221-447cf8-i686

操作系统及其版本：
Windows 10 x86_64

问题概述：
3个通过特定操作崩溃问题：
1.关于微软登录通过特定操作崩溃的问题
2.关于curseforge与modrinth无法进入的问题
3.关于curseforge与modrinth有概率导致启动器崩溃的问题

崩溃报告：无

启动参数：无

重现步骤：
问题1：
1. 打开启动器
2.点击玩家头像
3.进入第二个，微软登录
4.返回，不要关闭弹窗
5再次进入，启动器崩溃

问题2/3：
1. 打开启动器
2.进入模组下载页面
3.点击curseforge或modrinth
4.启动器报错，页面空白/崩溃

备注：
无

**Comment by Steve-xmh** [comment]
请让 Issue 一一对应每个问题，而不是挤在一起
