### ISSUE TITLE
建议添加authlib-injectar登录选项

### ISSUE THREAD

**Issue by zkitefly** [Steve-xmh/scl#7]
// 功能概述
// 你设想的功能是什么呢？
功能概述：建议添加authlib-injectar登录选项

// 问题关联
// 这个功能与当前启动器的某个短板有关吗？可以引用 Issue 哦！
问题关联：

// 备注
// 如果还有什么需要提及的话
备注：

**Comment by Steve-xmh** [comment]
在内测版本已经添加该登陆选项
