### ISSUE TITLE
[Bug] macOS 系统 1.1.0 版本 AuthLib登录报错

### ISSUE THREAD

**Issue by NevadaCities** [Steve-xmh/scl#73]
启动器版本号：1.1.0

操作系统及其版本：macOS Ventura 13.1

问题概述：AuthLib登录时报错：Read-Only File System, OS Error 30

崩溃报告：
```
暂无
```

启动参数：
```
-XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-UseParallelGC -XX:+UseG1GC -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:-DontCompileHugeMethods -XX:+TieredCompilation -Xmixed
```

重现步骤：

1. 打开启动器
2. 点击头像
3. 选择AuthLib登录
4. 输入API、账号、密码然后点击登录

备注：无

**Comment by Steve-xmh** [comment]
已更新 1.1.1，会陆续上传到 Github
