### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by Jack-Works** [Steve-xmh/scl#74]
您好！我发现仓库内的源代码似乎没有提供 UI 的部分，workspace 中的 5 个子项目都是 lib，没有 bin

**Comment by Steve-xmh** [comment]
是这样的，为了避免有恶意软件出现，GUI 部分的原代码是不开源的，还请谅解。
已有的开源库都是完整可用的代码，均可以自行取用并开发出自己的启动器。可以查阅 Rust 的相关开发资料，以了解如何将本库作为依赖使用在你的项目中。
之后可能会考虑制作一个简单的开源可用 DEMO 启动器供参考，但不会和 SCL 的页面完全一致。
