### ISSUE TITLE
启动器无法处理和保存微软的聊天公钥

### ISSUE THREAD

**Issue by LoveXiaoMan** [Steve-xmh/scl#75]
启动器版本号：Sharp Craft Launcher 1.1.1
操作系统及其版本：Windows 11 x86_64
问题概述：
现在不是有聊天举报系统嘛，每次正版登录，微软都会给每个用户一个聊天公钥，而被聊天公钥加密过的聊天，就可以被举报到微软，而这个聊天公钥呢，不是保存在游戏里，是每次在启动器登录时，微软会给到启动器里或启动器的文件里，而您的启动器没有保存正版聊天公钥的功能，如果正版服务器开启了强制聊天公钥的选项，因为没有获取到聊天公钥，那就没办法在游戏里发消息，强制聊天公钥这个server选项是服务端默认开启的；图片我已经截图到了您的QQ里
现在的大部分启动器的最新版本都没有保存聊天公钥这个功能，唯一能保存的只有PCL启动器的测试版本

**Comment by Steve-xmh** [comment]
已解决，虽然并不是这么解决的。是由于微软验证中的 `${user_type}` 参数有误，现已针对微软登录更换成 `msa`
PCL2 的原 Issue 是这个：https://github.com/Hex-Dragon/PCL2/issues/1221
