### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by milkice233** [Steve-xmh/scl#77]
启动器版本号：1.1.1

操作系统及其版本：Windows 10 x86_64

问题概述：使用Authlib登录第三方验证服务器时提示，IllegalArgumentException: The player requested doesn't match with that token

崩溃报告：
无

重现步骤：

1. 打开启动器
2. 点击登录，选择Authlib Injector第三方登录
3. 填入服务器地址，用户名和密码
4. 登陆失败，提示IllegalArgumentException: The player requested doesn't match with that token

备注：
第三方验证地址是https://mc.uv.uy/ ，可以注册个账号并使用SCL登录，可稳定复现该问题

**Comment by Steve-xmh** [comment]
已修正，预计下一个修订版本号推出
