### ISSUE TITLE
[Feature]任务栏进度条

### ISSUE THREAD

**Issue by FangFuJi1991** [Steve-xmh/scl#80]
首先，我在 下载游戏其它资源 时需要做其他事情，但是怎么才能快速地查看 下载进度 呢？
有啦！任务栏进度条！
应该懂吧 类似于这种：
![QHQ W%DFPEEW58BI_E0G1 H](https://user-images.githubusercontent.com/103358064/229992929-f570d68e-a9b5-4018-9f3d-24ca6196d9a3.png)
（客串的pcl2x
所以能做就感谢了~

**Comment by Steve-xmh** [comment]
已增加该功能，预计下一个修订版本号推出
