### ISSUE TITLE
(Bug) 删除的问题

### ISSUE THREAD

**Issue by FangFuJi1991** [Steve-xmh/scl#82]
~~删除被选中的版本时，启动按钮还会显示被删除的版本~~
2023.8.18修改
scl中存在一些关于删除的问题，
例如删除选中版本，启动按钮还会显示被删掉的版本。
删除一个手动添加的java时，不会重新选择到其他java。

**Comment by FangFuJi1991** [comment]
可能还有其他的，懒得写了= =

**Comment by Steve-xmh** [comment]
开发版本已修正，下一个修订版本号推出
