### ISSUE TITLE
将SCL-Core提交到crates.io

### ISSUE THREAD

**Issue by 0x002500** [Steve-xmh/scl#89]
将SCL-Core提交到crates.io，方便广大开发者基于SCL-Core开发出更多好玩的东西或者二次封装后开源

**Comment by Steve-xmh** [comment]
之前也有想过，不过个人还是觉得接口比较杂乱，也没时间撰写一些文档
可以先占个位，之后看哪位友人可以帮我编写文档了

**Comment by 0x002500** [comment]
好的，谢谢答复

**Comment by Steve-xmh** [comment]
核心模块已发布至 crates.io https://crates.io/crates/scl-core

**Comment by 0x002500** [comment]
执行效率好高，赞了
